### ISSUE TITLE
Faster download link for the driver

### ISSUE THREAD

**Issue by ShinjoKurumi** [intertiexd/raincandy_546.33GR#1]
The link I provided in Baidu Tieba is hosted on Baidu Net Disk, and it does "takes forever to download there without membership". I did provided more links that hosted on different cloud disk provider, however I can't provide these links on Tieba because they will simply delete my post.

For foreign users that need my modified driver, here is a a link hosted on huang1111 Cloud Disk, based on OneDrive for Business, which should provide faster download speed.

https://pan.huang1111.cn/s/7GqEHg

**Comment by intertiexd** [comment]
哇哦，参拜大佬~谢谢大佬给我们写的驱动——

**Comment by ShinjoKurumi** [comment]
嘿嘿~顺便说下，雨科的官网上有全部的网盘链接。
http://raincandy.1337.moe/nvcmpgpu/

**Comment by rmdnnYtta** [comment]
hep the link is expired
